# fly.toml app configuration file generated for bgpp on 2023-08-30T11:39:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bgpp"
primary_region = "waw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
